// Dados de teste da tela de Monitoramento de Dispositivos & Catracas.
// Quando a API Java estiver pronta, o monitoramentoService.js troca essas funções
// por chamadas reais (axios/WebSocket) — a página não precisa mudar.

export const estacoesMock = [
  {
    id: 1,
    numero: '01',
    nome: 'Ponto 01 • Portaria Principal (Entrada A)',
    descricao: 'Catraca Flap de Alta Velocidade com Terminal Facial Superior Integrado',
    statusGeral: 'operacional',
    catraca: {
      nome: 'Catraca Flap 01',
      tipo: 'Catraca Física',
      modelo: 'Digicon D-Flow 2000',
      status: 'online',
      ip: '192.168.10.21',
      porta: '8080 (OK)',
      ciclos: '1.420 giros',
      rele: 'Normal (Fechada)',
      ping: 11,
      firmware: 'v3.2',
    },
    facial: {
      nome: 'Terminal Facial 01',
      modelo: 'Intelbras FacePass Pro HD',
      status: 'reconhecendo',
      ip: '192.168.10.22',
      stream: 'Porta 554 (OK)',
      precisao: '99.4%',
      bancoFaces: '1.428 faces sync',
      progressoSync: null,
      ultimaSync: 'há 32s',
    },
  },
  {
    id: 2,
    numero: '02',
    nome: 'Ponto 02 • Portaria Principal (Entrada B)',
    descricao: 'Catraca Flap Acesso Geral Alunos com Terminal Facial de Leitura Rápida',
    statusGeral: 'operacional',
    catraca: {
      nome: 'Catraca Flap 02',
      tipo: 'Catraca Física',
      modelo: 'Digicon D-Flow 2000',
      status: 'online',
      ip: '192.168.10.23',
      porta: '8080 (OK)',
      ciclos: '1.890 giros',
      rele: 'Normal (Fechada)',
      ping: 14,
      firmware: 'v3.2',
    },
    facial: {
      nome: 'Terminal Facial 02',
      modelo: 'Intelbras FacePass Pro HD',
      status: 'reconhecendo',
      ip: '192.168.10.24',
      stream: 'Porta 554 (OK)',
      precisao: '99.1%',
      bancoFaces: '1.428 faces sync',
      progressoSync: null,
      ultimaSync: 'há 1m 15s',
    },
  },
  {
    id: 3,
    numero: '03',
    nome: 'Ponto 03 • Portão Docentes / Administrativo',
    descricao: 'Catraca Pedestre Braço Tripé com Terminal Facial de Alta Resolução',
    statusGeral: 'sincronizando',
    catraca: {
      nome: 'Catraca Pedestre 03',
      tipo: 'Braço Tripé',
      modelo: 'Telemática Box Pedestre',
      status: 'online',
      ip: '192.168.10.31',
      porta: '8080 (OK)',
      ciclos: '860 giros',
      rele: 'Normal (Fechada)',
      ping: 16,
      firmware: 'v2.9',
    },
    facial: {
      nome: 'Terminal Facial 03',
      modelo: 'Intelbras FacePass Pro HD',
      status: 'sincronizando',
      ip: '192.168.10.32',
      stream: 'Porta 554 (OK)',
      precisao: '99.7%',
      bancoFaces: '1.200 / 1.428',
      progressoSync: 84,
      ultimaSync: null,
    },
  },
  {
    id: 4,
    numero: '04',
    nome: 'Ponto 04 • Acesso Oficinas / Metalmecânica',
    descricao: 'Catraca Torniquete Industrial com Terminal Facial Blindado IP67',
    statusGeral: 'operacional',
    catraca: {
      nome: 'Catraca Torniquete 04',
      tipo: 'Torniquete Pesado',
      modelo: 'Wolpac Titan Heavy 4X',
      status: 'online',
      ip: '192.168.10.41',
      porta: '8080 (OK)',
      ciclos: '2.140 giros',
      rele: 'Normal (Fechada)',
      ping: 18,
      firmware: 'v4.0',
    },
    facial: {
      nome: 'Terminal Facial 04',
      modelo: 'Hikvision MinMoe Ultra-Rugged',
      status: 'reconhecendo',
      ip: '192.168.10.42',
      stream: 'Porta 554 (OK)',
      precisao: '99.6%',
      bancoFaces: '1.428 faces sync',
      progressoSync: null,
      ultimaSync: 'há 50s',
    },
  },
];

export function logsMockDaEstacao(nomeEstacao) {
  return [
    {
      tipo: 'facial',
      titulo: '[FACIAL_MATCH] AUTORIZADO',
      hora: '14:38:12.441',
      texto: `Biometria facial validada com 99.8% match em ${nomeEstacao}. Liberando relé mecânico.`,
    },
    {
      tipo: 'rele',
      titulo: '[RELAY_PULSE] CATRACA_FLAP',
      hora: '14:38:12.602',
      texto: 'Comando eletromecânico enviado: abertura das aletas por 4.000ms. Giro confirmado pelo sensor óptico.',
    },
    {
      tipo: 'heartbeat',
      titulo: '[HEARTBEAT] SYNC_OK',
      hora: '14:35:00.012',
      texto: 'Keep-alive ACK simultâneo recebido. Latência catraca e facial dentro do esperado.',
    },
    {
      tipo: 'alerta',
      titulo: '[ANTI_TAILGATING] SENSOR_ALERTA',
      hora: '13:58:44.209',
      texto: 'Dupla passagem bloqueada pelo feixe infravermelho inferior. Aletas fechadas com segurança imediata.',
    },
  ];
}